# Generated by Django 3.0.8 on 2020-07-08 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('Restaurant food', 'Restaurant food'), ('Travel news', 'Travel news '), ('Modern technology', 'Modern technology '), ('Product', 'Product '), ('Inspiration', 'Inspiration '), ('health care', 'health care')], default='--', max_length=120),
        ),
        migrations.AlterField(
            model_name='blog',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.today),
        ),
    ]
