# Generated by Django 3.0.8 on 2020-07-13 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0002_blogger_about'),
        ('naiapp', '0006_auto_20200711_2014'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
