# Generated by Django 3.0.8 on 2020-07-14 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naiapp', '0008_auto_20200714_2131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='Title',
        ),
    ]
