# Generated by Django 3.0.8 on 2020-07-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naiapp', '0009_auto_20200714_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Title',
            field=models.CharField(max_length=120),
        ),
    ]
