# Generated by Django 3.0.8 on 2020-07-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogger',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
