# Generated by Django 3.0.8 on 2020-07-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='about',
            field=models.TextField(blank=True),
        ),
    ]
