# Generated by Django 3.0.8 on 2020-07-14 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_seller_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='about',
        ),
    ]
