# Generated by Django 3.0.8 on 2020-07-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_auto_20200707_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='summary',
            field=models.TextField(default=''),
        ),
    ]
