# Generated by Django 3.0.8 on 2020-07-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_auto_20200707_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cat',
            field=models.CharField(choices=[('Category1', 'Electronic'), ('Category2', 'Clothing'), ('Category3', 'Accessories')], default='', max_length=120),
        ),
    ]
