# Generated by Django 3.0.8 on 2020-07-10 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
        ('Product', '0012_auto_20200709_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.Seller'),
        ),
    ]
