# Generated by Django 3.0.8 on 2020-07-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0015_auto_20200711_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.CharField(choices=[('Electronic', 'Electronic'), ('Clothing', 'Clothing'), ('Accessories', 'Accessories')], default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='product',
            name='pic',
            field=models.ImageField(upload_to=''),
        ),
    ]
