# Generated by Django 3.0.8 on 2020-07-14 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0021_auto_20200714_1943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='cat_title',
            new_name='title',
        ),
    ]
