# Generated by Django 3.0.8 on 2020-07-14 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Product', '0018_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=1, max_digits=100)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Product.Product')),
            ],
        ),
    ]
