# Generated by Django 3.0.8 on 2020-07-14 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20200714_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='total',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=100000),
            preserve_default=False,
        ),
    ]
