# Generated by Django 3.0.8 on 2020-07-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_cartitem_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=100000),
        ),
    ]
